#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-airlift-units
Version  : 1.0
Release  : 1
URL      : https://github.com/airlift/units/archive/1.0.tar.gz
Source0  : https://github.com/airlift/units/archive/1.0.tar.gz
Source1  : https://repo1.maven.org/maven2/io/airlift/units/1.0/units-1.0.jar
Source2  : https://repo1.maven.org/maven2/io/airlift/units/1.0/units-1.0.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: mvn-airlift-units-data = %{version}-%{release}

%description
No detailed description available

%package data
Summary: data components for the mvn-airlift-units package.
Group: Data

%description data
data components for the mvn-airlift-units package.


%prep
%setup -q -n units-1.0

%build

%install
mkdir -p %{buildroot}/usr/share/java/.m2/repository/io/airlift/units/1.0
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/io/airlift/units/1.0/units-1.0.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/io/airlift/units/1.0
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/io/airlift/units/1.0/units-1.0.pom


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/io/airlift/units/1.0/units-1.0.jar
/usr/share/java/.m2/repository/io/airlift/units/1.0/units-1.0.pom
